### ISSUE TITLE
[BUG] Fusion doesn't allow spaces in unique_ids (but tbh I kinda like that?)

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-fusion#101]
**Describe the bug**
```
sources:
  - name: google_sheets_airbyte
    quoting:
      database: false
      schema: false
      identifier: true
    database: GOOGLE_SHEETS_AIRBYTE
    schema: PUBLIC
    tables:
      - name: CHARGEBEE_DISCARDS
      - name: "LIVE INVOICE FIXES"
```

On dbt parse, it raises `error: dbt0102: Resource name 'google_sheets_airbyte.LIVE INVOICE FIXES' contains forbidden characters`

This is because of [(currently-private) code here](https://github.com/dbt-labs/fs/blob/79d7bd953bb32d11438fc03e68873c41c2fe601b/fs/sa/crates/dbt-parser/src/resolve/resolve_properties.rs#L310-L323) which is meant to be for [enforcing the no spaces in resource names deprecation](https://docs.getdbt.com/reference/global-configs/behavior-changes#no-spaces-in-resource-names). 

I actually think this is the correct behaviour. The docs even specify that sources can't have spaces, but I think that in turn is a mistake because we can't control the structure of sources. 

So I think we should: 
- change the unique_id generation to strip spaces from sources in Fusion
- backport this behaviour to dbt Core as well 

It would change how unique IDs are generated for a small number of models but seems for the best. 

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
b12 

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**

Open [source_quoting.zip](https://github.com/user-attachments/files/20514597/source_quoting.zip)
- Run a dbt parse with Fusion, notice it errors and that no manifest is generated
- Run a dbt parse with Core, notice it succeeds and that the manifest contains `"source.source_quoting.google_sheets_airbyte.LIVE INVOICE FIXES"`

In both cases, the column quoting rules work correctly, so it's not that (you'll have to rename the source to something else to see this in Fusion, since it fails before it writes a manifest)

**Expected behavior**
Unique ID to be `"source.source_quoting.google_sheets_airbyte.LIVE__INVOICE__FIXES"` or something
