### ISSUE TITLE
[FEAT] Support `anchors` top-level key for yaml anchors (so we don't throw unused key warnings)

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-fusion#116]
https://getdbt.slack.com/archives/C088YCAB6GH/p1748641065741219

**Describe the bug**
There are two ways to use YAML anchors: 

### Make a snippet out of one piece of a bigger YAML object
```
version: 2
# thanks Josh https://joshdevlin.com/blog/yaml-repeating-sections/#putting-it-all-together
# this works correctly because the anchor definition is part of a real model, not a standalone component
models:
  - name: model_one
    columns:
      - name: id
        tests: &unique_not_null
          - unique
          - not_null
      - name: col_a
      - name: col_b
  - name: model_two
    columns:
      - name: id
        tests: *unique_not_null
      - name: col_c
      - name: col_d
```

### Define a standalone snippet of YAML which is reused in other objects but is not itself meant to be used

```
# This columns anchor is being correctly embedded into the models, but it's also being rejected as an unacceptable key at the top level of the YAML file
columns: &id_column
  - name: id
    description: This is a unique identifier for a policy.
    data_tests:
      - not_null

models:
    - name: my_first_model
      description: This is a description for the first model
      columns: *id_column

    - name: second
      description: This is a description for the second model
      columns: *id_column
```

We support the first pattern totally fine, but the second pattern leads to the standalone components also being validated:
```
dbt0102: No tables defined for source 'hx_base' in file 'models/broken_example_two/source.yml'.
```
or
```
dbt1060: Ignored unexpected key `"columns"`. YAML path: `columns`.
  --> models/broken_example_one/column_spec.yml:2:1
```

I think this is just because dbt Core didn't care about unexpected YAML fragments, but it could also be a divergence in behaviour (especially for the source example in the attached project). 
Note that all the YAML is correctly being expanded and handled (i.e. the sources are being created, and the tests and columns are being correctly attached to the models)

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
beta 12

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**
- Open this project [anchor_yaml.zip](https://github.com/user-attachments/files/20543044/anchor_yaml.zip)
- Run dbt parse

**Expected behavior**
- No warnings. Maybe we need a way to do like a `#noqa` comment for an anchor or something? 
- See also https://github.com/dbt-labs/fs/issues/1324 from earlier this year

**Comment by venkaa28** [comment]
Some thoughts!

For this sources block:

```
sources:
sources:
  # This base source is being treated as a standalone source, rather than just a building block for the other two sources
  - &hx_base
    name: hx_base
    database: raw_prod

  - <<: *hx_base
    name: first_schema
    schema: hx_renew_airline
    tables:
      - name: airline

  - <<: *hx_base
    name: second_schema
    schema: hx_some_other_schema
    tables:
      - name: buses
```

The warning 
`warning: dbt0102: No tables defined for source 'hx_base' in file 'models/broken_example_two/source.yml'.`
is valid because hx_base has no tables defined. The other sources correctly inherit the database via YAML merging!

This warning is new to Fusion and highlights a subtle difference between dbt and FS. One potential solution is introducing a top-level anchors field, where users can define all anchor blocks to prevent unnecessary warnings.

Similarly, the following warning could also be addressed with a top-level anchors field:

`warning: (will error post-beta) dbt1060: Ignored unexpected key "columns". YAML path: columns.
  --> models/broken_example_one/column_spec.yml:2:1`.

Great suggestion, @b-per !

**Comment by joellabes** [comment]
> Regarding this error the user is seeing:
> 
> `error: dbt1013: YAML error: mapping values are not allowed in this context at line 1 column 18` linked [here](https://getdbt.slack.com/archives/C088YCAB6GH/p1748641421817989?thread_ts=1748641065.741219&cid=C088YCAB6GH)
> 
> I'm not able to reproduce this!

This was some invalid YAML which was resolved in the repro project. I made an issue to have a clearer error message though: https://github.com/dbt-labs/dbt-fusion/issues/139

**Comment by dbeatty10** [comment]
_Potential_ acceptance criteria:

> there is no warning raised if a source is defined that doesn’t contain any tables

**Comment by joellabes** [comment]
For those of you following along at home, here's a couple of things we tried that didn't work/we didn't like:

## 🙅‍♂  Doing a dedicated anchors block

```yml
anchors: #anything in here would be untyped and not validated
  - &hx_base
    name: hx_base
    database: raw_prod

    columns: &_id_column
     - name: id
       description: This is a unique identifier for a policy.
       data_tests:
        - not_null

models:
  - name: my_first_model
    description: This is a description for the first model
    columns: *_id_column

sources:
  - <<: *hx_base
    name: first_schema
    schema: hx_renew_airline
    tables:
      - name: airline

  - <<: *hx_base
    name: second_schema
    schema: hx_some_other_schema
    tables:
      - name: buses
```

but it would mean you wouldn't be able to combine lists and dicts. That `columns` dict is actually now part of the `&hx_base` source template. So you'd have to put lists somewhere like this, which I haaaaaaate. 

```yml
anchors:
  lists: #ew!
    - &hx_base
      name: hx_base
      database: raw_prod
  columns: &_id_column
     - name: id
       description: This is a unique identifier for a policy.
       data_tests:
        - not_null
```

--------

## 🙅‍♂ Using a leading underscore to indicate things to ignore 

We also thought we could do something like having a leading underscore to mark the second type of anchor, sort of like [telling Rust to ignore an unused variable](https://stackoverflow.com/questions/48361537/why-do-underscore-prefixed-variables-exist):

But that didn't work for the second type of anchor (_Define a standalone snippet of YAML which is reused in other objects but is not itself meant to be used_)

```
sources:
  - &hx_base
    _name: hx_base
    _database: raw_prod

  - <<: *hx_base
    name: first_schema
    schema: hx_renew_airline
    tables:
      - name: airline

  - <<: *hx_base
    name: second_schema
    schema: hx_some_other_schema
    tables:
      - name: buses
```

because `_name` isn't valid once it's merged in. It's also not possible to treat anchors' names like this (e.g. `&_hx_base`), but Ani explained why on a call instead of in chat so I can't remember why anymore 😓

**Comment by sadboy** [comment]
> but it would mean you wouldn't be able to combine lists and dicts

Not sure I'm following. `anchors` is just a Yaml key, its value can be any Yaml value, so you should be able to cut-paste whatever anchor you had before under it. If you have multiple unrelated anchor values, then a list is probably the simplest way to go, e.g.:

```
anchors: #anything in here would be untyped and not validated
  - &hx_base
    name: hx_base
    database: raw_prod

 - columns: &_id_column
     - name: id
       description: This is a unique identifier for a policy.
       data_tests:
        - not_null
```
but a map with explicit top-level keys would certainly also work.
