### ISSUE TITLE
[FEAT] Have a better error message for invalid YAML documents

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-fusion#139]
**Is your feature request related to a problem? Please describe.**
Consider this YAML:
```
# The colon after the anchor name is invalid
columns: &id_column:
  - name: id
    description: This is a unique identifier for a policy.
    data_tests:
      - not_null

models:
    - name: my_first_model
      description: This is a description for the first model
      columns: *id_column

    - name: second
      description: This is a description for the second model
      columns: *id_column
```

dbt Core gives a better error message: ([see implementation](https://github.com/dbt-labs/dbt-core/blob/87584c73b016eacbed70c2cd90f6688e39fdfc86/core/dbt/clients/yaml_helper.py#L17-L25))

```
(dbt-prod) joel@Joel-Labes anchor_yaml % dbt parse -q
23:29:29  Encountered an error:
Parsing Error
  Error reading anchor_yaml: broken_example_one/column_spec.yml - Runtime Error
    Syntax error near line 2
    ------------------------------
    1  | # This columns anchor is being correctly embedded into the models, but it's also being rejected as an unacceptable key at the top level of the YAML file
    2  | columns: &id_column:
    3  |   - name: id
    4  |     description: This is a unique identifier for a policy.
    5  |     data_tests:
    
    Raw Error:
    ------------------------------
    mapping values are not allowed in this context
      in "<unicode string>", line 2, column 20
```
than the dbt Fusion engine:

```
error: dbt1013: YAML error: mapping values are not allowed in this context at line 2 column 20
  --> <unknown>:2:20
```

**Is your feature request related to a particular component of the dbt Fusion Engine**
- [x] CLI Features
- [ ] Adapter or Database Driver Features
- [ ] SQL Understanding Features
- [ ] VS Code extension

**Describe the solution you'd like**
The nice error message that dbt Core has

**Comment by joellabes** [comment]
## Workaround: 

Running `dbtf parse --show progress` will list out every YAML file as it goes. I don't think it's guaranteed to list them in the order that they're being processed, but in my experience it almost always does.

```
(dbt-prod) joel@Joel-Labes joel-sandbox % dbtf parse --show progress
dbt-fusion 2.0.0-beta.15
   Loading ~/.dbt/profiles.yml
   Loading packages.yml
   Loading dbt_project.yml
   Loading dbt_packages/dbt_utils/dbt_project.yml
   Loading dbt_internal_packages/dbt-adapters/dbt_project.yml
   Loading dbt_internal_packages/dbt-snowflake/dbt_project.yml
   Parsing models/hi.yml
   Parsing models/marts/customers.yml
   Parsing models/marts/locations.yml
   Parsing models/marts/order_items.yml
   Parsing models/marts/orders.yml
error: dbt1013: YAML error: did not find expected key at line 9 column 9, while parsing a block mapping at line 5 column 9
  --> <unknown>:9:9
  Finished 'parse'  with 1 error in 252ms 771us
```

![Image](https://github.com/user-attachments/assets/6bc92f53-3006-469e-a95b-36a267a6fe7c)

**Comment by joellabes** [comment]
@daweimau in its own way, that is actually helpful! It means that Fusion can't even load your profiles.yml file (that's the first file that is attempted to be loaded). 

I can't _quite_ replicate your issue, but I got close by wrapping my entire profiles.yml file in curly braces:

```
{ 
some_profile: 
  target: dev
  outputs: 
    dev: 
.....
}
```

```
joel@Joel-Labes simulated_project_100_models % dbt parse --show progress
dbt-fusion 2.0.0-beta.23
   Loading ~/.dbt/profiles.yml
error: dbt1013: YAML error: did not find expected ',' or '}' at line 3 column 9, while parsing a flow mapping
  --> ../../../../.dbt/profiles.yml:3:9
  Finished 'parse'  with 1 error in 1ms 338us
```

We're on the same beta, but my one writes out the Loading line before failing 🤷‍♂ 

Anyway, could you try checking if your profiles.yml has anything weird in it? Flow mappings are inline with `{}` so the missing comma in `{key1: value1 key2: value2}` would be such an error for example.

**Comment by daweimau** [comment]
Oh, interesting!

My profiles.yml is very boring (no curly braces here). Included the full (sanitised) content below. It's located at `~/.dbt/profiles.yml`, and works fine with dbt core...

```yml
AmberBI:
  outputs:
    dev:
      account: oaNNNNN.ap-southeast-2
      authenticator: key_pass
      connect_retries: 1
      connect_timeout: 10
      database: AMBERDEV
      private_key_passphrase: *********
      private_key_path: /Users/david/.dbt/private.key
      role: DBTSTAGINGROLE
      schema: MASTER
      type: snowflake
      user: abc@website.com
      warehouse: DBT_TRANSFORM
  target: dev
AmberLanding:
  outputs:
    dev:
      account: oaNNNNN.ap-southeast-2
      authenticator: key_pass
      connect_retries: 1
      connect_timeout: 10
      database: AMBERLANDING
      private_key_passphrase: *********
      private_key_path: /Users/david/.dbt/private.key
      role: DBTSTAGINGROLE
      schema: MASTER
      type: snowflake
      user: abc@website.com
      warehouse: DBT_TRANSFORM
  target: dev
default:
  outputs:
    dev:
      account: oaNNNNN.ap-southeast-2
      authenticator: key_pass
      connect_retries: 1
      connect_timeout: 10
      database: AMBERDEV
      private_key_passphrase: *********
      private_key_path: /Users/david/.dbt/private.key
      role: DBTSTAGINGROLE
      schema: MASTER
      type: snowflake
      user: abc@website.com
      warehouse: DBT_TRANSFORM
  target: dev
mytmpdbt:
  outputs:
    dev:
      account: oa123
      database: abc
      password: abc
      role: abc
      schema: abc
      threads: 1
      type: snowflake
      user: david
      warehouse: abc
  target: dev
```
