### ISSUE TITLE
[BUG] Projects using unit testing on incremental models fail with `error: dbt9002: Invalid given input: this`

### ISSUE THREAD

**Issue by jimioksman** [dbt-labs/dbt-fusion#150]
**Describe the bug**
Running a command that parses a project that uses unit testing on incremental models fails with `error: dbt9002: Invalid given input: this`

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
`dbt-fusion 2.0.0-beta.14`

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**
Have an incremental model, which uses unit testing.

For example, model yaml:

```yml
unit_tests:
  - name: my_incremental_model_test
    model: my_incremental_model
    overrides:
      macros:
        is_incremental: true
    given:
      - input: this
```

Run any dbt command that parses the project: run, compile, parse, etc.

Produces the following error:
`error: dbt9002: Invalid given input: this`

**Expected behavior**
Project parses successfully without errors.

**Operating System and CPU Type (please complete the following information):**
* Linux
* X86
