### ISSUE TITLE
[FEAT] [VSCE] invalid unit test configs are flagged on the model they test, not in their YAML file

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-fusion#162]
**Is your feature request related to a problem? Please describe.**
Imagine this unit test: (or open this repro project [unit_test_lsp_missing_column.zip](https://github.com/user-attachments/files/20599424/unit_test_lsp_missing_column.zip))
```
unit_tests:
  - name: demo_unit_test
    model: downstream
    given:
      - input: ref('upstream')
        rows:
          - {id: 1}
    expect:
      rows:
        - {nonexistent_column: 1}
```

During a dbt compile, an error is raised:
```
error: dbt0227: No column NONEXISTENT_COLUMN found. Available are ANALYTICS_JLABES_DEV_DOWNSTREAM_ACTUAL.CREATED_AT, ANALYTICS_JLABES_DEV_DOWNSTREAM_ACTUAL.NAME, ANALYTICS_JLABES_DEV_DOWNSTREAM_ACTUAL.ID
  --> models/example/downstream.sql:15:20 (target/compiled/models/example/demo_unit_test.sql:15:20)
```

This error is correct, and it points to the correct line of code in `target/compiled`, but it primarily points at the actual model which means the VSCE highlights the issue there. (This is maybe a sibling to #158 and #159)

**Is your feature request related to a particular component of the dbt Fusion Engine**
- [x] CLI Features
- [ ] Adapter or Database Driver Features
- [x] SQL Understanding Features
- [x] VS Code extension

**Describe the solution you'd like**
Ideally, the `-->` would point to the YAML file, and the VSCE would highlight the offending line of YAML
```
error: dbt0227: No column NONEXISTENT_COLUMN found. Available are ANALYTICS_JLABES_DEV_DOWNSTREAM_ACTUAL.CREATED_AT, ANALYTICS_JLABES_DEV_DOWNSTREAM_ACTUAL.NAME, ANALYTICS_JLABES_DEV_DOWNSTREAM_ACTUAL.ID
  --> models/example/schema.yml:12:12 (target/compiled/models/example/demo_unit_test.sql:15:20)
```

**Additional context**

<img width="1468" alt="Image" src="https://github.com/user-attachments/assets/06b50095-26ce-44a6-90b6-28bb26c14990" />
