### ISSUE TITLE
[BUG] Fusion requires all env vars to be set in `profiles.yml`

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-fusion#174]
**Describe the bug**

If several targets are setup in `profiles.yml`, Fusion requires env vars to be set for all the targets, even for the targets that are not supposed to be run in the current context.

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
```
dbt-fusion 2.0.0-beta.15
```

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**

Create a profile with different targets, each target requiring some env vars, with no default value:

```
outputs:
    target: dev
    dev:
      account: abcd
      client_session_keep_alive: false
      connect_retries: 0
      connect_timeout: 10
      database: db
      password: "{{ env_var('DBT_PASS_DEV') }}"
      retry_all: false
      retry_on_database_errors: false
      role: role
      schema: schema
      threads: 4
      type: snowflake
      user: user
      warehouse: warehouse
    prod:
      account: abcd
      client_session_keep_alive: false
      connect_retries: 0
      connect_timeout: 10
      database: db
      password: "{{ env_var('DBT_PASS_PROD') }}"
      retry_all: false
      retry_on_database_errors: false
      role: role
      schema: schema
      threads: 4
      type: snowflake
      user: user
      warehouse: warehouse
```

- set the env var for `DBT_PASS_DEV` but NOT for `DBT_PASS_PROD`
- doing a `dbtf compile` raises an error saying that `DBT_PASS_PROD` is not provided

Thiis not the case for dbt Core.

**Expected behavior**
Fusion works if we provide the env vars for the current target, even if other targets have other env vars that are not provided.
