### ISSUE TITLE
[BUG] Tests with Jinja templated parameters are not rendered properly

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-fusion#177]
**Describe the bug**

Some data tests take additional parameters.
Those parameters are often hard coded, but in dbt-core they can be a Jinja template.

Fusion doesn't render the template accurately which leads to invalid SQL. The same test works on dbt-core.

The same behavior was seen for models and for seeds.

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
```
dbt-fusion 2.0.0-beta.15
```

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**

- create a model called `my_model.sql` like this `select 1 as id, 2 as name`
- create a data test like this (`compare_columns` is templated`)
```yaml
models:
  - name: my_model
    data_tests:
      - dbt_utils.equality:
          name: test_repro
          compare_model: ref('my_model')
          compare_columns:
            - "{{ 'id' if true else 'name' }}"
```
- `dbtf compile` generates the following test
```
{{ dbt_utils.test_equality(compare_columns=["{{ 'id' if true else 'name' }}"], compare_model=ref('my_model'), model=get_where_subquery(ref('my_model')), name="test_repro") }}
```
- which generates the invalid SQL
```sql
with a as (

    select * from analytics_DEV.dbt_bperigaud.my_model

),

b as (

    select * from analytics_DEV.dbt_bperigaud.my_model

),

a_minus_b as (

    select {{ 'id' if true else 'name' }} from a
    

    except
...
```

The generated test should be one the following instead:
```
# unrendered
{{ dbt_utils.test_equality(compare_columns=['id' if true else 'name'], compare_model=ref('my_model'), model=get_where_subquery(ref('my_model')), name="test_repro") }}
# or rendered
{{ dbt_utils.test_equality(compare_columns=['id'], compare_model=ref('my_model'), model=get_where_subquery(ref('my_model')), name="test_repro") }}
```

**Expected behavior**
Fusion should allow test parameters to contain Jinja logic
