### ISSUE TITLE
[BUG] [DBRX] seed config `column_types` not respected

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-fusion#190]
**Describe the bug**

related: #189

adding manual override for [`column_types`](https://docs.getdbt.com/reference/resource-configs/column_types) isn't respected on Databricks, so far as I can tell

```yml
# dbt_project.yml
seeds:
  raw_orders:
    +config:
      column_types:
        id: integer
        user_id: integer
        order_date: string
        status: string
```

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**
Please submit one of the following
see #189 

**Expected behavior**

The Databricks web UI should show a table column schema that matches the configuration in my `dbt_project.yml`
