### ISSUE TITLE
[BUG] Can't use var inside a test's where config

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-fusion#191]
### Describe the bug

If you reference a variable within a model column test's [`where` config](https://docs.getdbt.com/reference/resource-configs/where), you get errors like below.

**Errors**

on Snowflake
```
dbt0101: missing ')' at 'var_name'
  --> target/generic_tests/accepted_values_a_my_value__0.sql:2:1
```

on Databricks
```
dbt0101: no viable alternative at input 'with all_values as (

    select
        my_value as value_field,
        count(*) as n_records

    from (select * from `fusion_dev`.`dev`.`a` where name != '{{ var('var_name'
  --> target/generic_tests/accepted_values_a_my_value__0.sql:2:1
```

### To Reproduce

The below should be sufficient, but for full repro see [this internal repro](https://github.com/dbt-labs/scratch/pull/11)

```sql
-- models/a.sql
select 0 as my_value, 'walle' as name
union all
select 1 as my_value, 'EVE' as name
```

```yml
# excerpt of dbt_project.yml 
vars:
  var_name: 'EVE'
```

YAML
```
# models/a.yml
models: 
  - name: a
    description: a model for pals
    columns: 
      - name: my_value
        tests: 
          - accepted_values: 
              values: [0]
              config:
                # where: "name != 'EVE'" # this works!
                where: "name != '{{ var('var_name') }}'" # this does not work!
```
### Other
**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**

beta.16

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [X] YES
- [ ] NO

**Expected behavior**

No bug!

**Screenshots**

**Operating System and CPU Type (please complete the following information):**
* Mac/Windows/Linux?
* X86 or ARM?
