### ISSUE TITLE
[BUG] dbt Fusion doesn't do query tags for data tests (using `dbt_snowflake_query_tags` package)

### ISSUE THREAD

**Issue by jeff-skoldberg-gmds** [dbt-labs/dbt-fusion#205]
**Describe the bug**
Using `- package: get-select/dbt_snowflake_query_tags` to set query tags, models are tagged properly.  However, the query tag is `unset` in Snowflake before running the tests.

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
dbt-fusion 2.0.0-beta.19

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**
1. Open [this workspace](https://github.com/dbt-labs/scratch/tree/main/repros/fusion-205)
2. Follow the instructions in the README

Or:

1. clone jaffle-sandbox (git@github.com:dbt-labs/jaffle-sandbox.git)
1. optional, but easier to build the project wide open once before continuing.
1. `packages.yml`
    ```yaml
    packages:
      - package: get-select/dbt_snowflake_query_tags
        version: [">=2.0.0", "<3.0.0"]
    ```
    `dbt_project.yml`:
    ```yaml
    dispatch:
      - macro_namespace: dbt
        search_order:
          - <YOUR_PROJECT_NAME>
          - dbt_snowflake_query_tags
          - dbt
    
    query-comment:
      comment: '{{ dbt_snowflake_query_tags.get_query_comment(node) }}'
      append: true
    ```
1. assuming you did step 2, run this: `dbt build -s customers`
1. observe snowflake query history has tags for the model and other DDL, but not for tests (see screenshots below)
1. optional: create a venv and run dbt core and observe how it is different.  every query gets tagged.

**Expected behavior**
query tag should not be unset prematurely

**Screenshots**
dbt core:

![Image](https://github.com/user-attachments/assets/2649c267-f9e8-49b0-9ca0-b6ef999a1804)

vs dbt Fusion:
![Image](https://github.com/user-attachments/assets/505ae16a-affc-4dc6-8c8e-fdfa8705d218)

**Operating System and CPU Type (please complete the following information):**
mac / snowflake
