### ISSUE TITLE
[FEAT] Snowflake External OAuth: Allow access tokens when authenticating with profiles.yml

### ISSUE THREAD

**Issue by erlendhbarstad** [dbt-labs/dbt-fusion#259]
**Is your feature request related to a problem? Please describe.**
When authenticating using `oauth` to Snowflake with dbt-fusion from VS Code, you are limited to use the Security Integration type `Snowflake OAuth`. Thus, the following values in your `profiles.yml` file are required:
- oauth_client_secret
- oauth_client_id
- token (refresh token)

This is also described in your code [here](https://github.com/dbt-labs/dbt-fusion/blob/2e698377d78be0353eaa0e0b13207376d08fae82/crates/dbt-xdbc/src/database.rs#L205).

With the current platform setup we have combined with our security requirements, we like dbt-fusion to support `external oauth` in Snowflake. Hence, it will be possible to **only** use access tokens directly to Snowflake in our profiles.yml file. See examples down below.

**Is your feature request related to a particular component of the dbt Fusion Engine**
- [ ] CLI Features
- [x] Adapter or Database Driver Features
- [ ] SQL Understanding Features
- [ ] VS Code extension

**Describe the solution you'd like**
When using dbt Core, you have the possibility to choose whether to use an access token **or** client ID, secret, and refresh token. The solution is described [here](https://github.com/dbt-labs/dbt-adapters/blob/7a7346892415598c3b5901a76ba4ed9cd22084fd/dbt-snowflake/src/dbt/adapters/snowflake/connections.py#L206).

Preferred profiles.yml when not adding client id+secret:
```yaml
      type: snowflake
      schema: DBT
      database: DEV
      role: my_role
      authenticator: oauth
      token: **my_access_token_123**
      ...
```

The current `profiles.yml`:
 ```yaml
      type: snowflake
      schema: DBT
      database: DEV
      role: my_role
      authenticator: oauth
      oauth_client_id: '123'
      oauth_client_secret: '123'
      token: 'my_refresh_token_123'
      ...
```

**Describe alternatives you've considered**
Move our developers from an automatic workflow with a pre defined profiles.yml to external browser authentication.
