### ISSUE TITLE
[BUG] Using `authenticator: externalbrowser` isn't possible in Fusion in a "headless" environment

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-fusion#263]
**Describe the bug**

When running in a headless machine/environment (Docker, GH action, SSH-ing to a server), dbt-core and Fusion behave differently if the authentication is set to `externalbrowser`

In dbt-core, we get the following:
```
Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Going to open: https://[...] to authenticate...
We were unable to open a browser window for you, please open the url above manually then paste the URL you are redirected to into the terminal.
Enter the URL the SSO URL redirected you to: 
```

When we click on the URL, and go through the flow, we get an error at the final redirect but copy/pasting it to the terminal makes the authentication successful 

In Fusion we get
```
[Snowflake] Failed to launch browser automatically: exec: "xdg-open,x-www-browser,www-browser": executable file not found in $PATH
[Snowflake] To authenticate, please manually open the following URL in your browser:

https://[...[

[Snowflake] Waiting for you to complete authentication in your browser...
```
But there is no way to paste the result we get when the redirect fails

---

`snowflake-connector-python` has some code to check if the URL was opened correctly or not: https://github.com/snowflakedb/snowflake-connector-python/blob/7ac23578fa906cf9e969a6fff2ed4a202a7b69b0/src/snowflake/connector/auth/webbrowser.py#L161-L167

The Go SDK doesn't seem to have the same logic.

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
Beta 24

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**
See above, just try to run dbt/Fusion in a headless env with authentication set to like this

```
my-profile:
  outputs:
    dev:
      authenticator: externalbrowser
      account: myaccount
      database: my_database
      role: my_role
      schema: my_schema
      type: snowflake
      user: my.user
      warehouse: my_warehouse
  target: dev
```

**Expected behavior**
We'd want Snowflake allowing using `authenticator: externalbrowser` in a headless env.
