### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-fusion#277]
**Describe the bug**

```
jinja_profiles_example:
  outputs:
    dev:
      type: snowflake
      threads: 8
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', default='none') }}"
      user: username
      private_key_path: /path/to/rsa_key.p8
      role: role
      database: db
      warehouse: wh
      schema: schema
  
  target: dev
```

This was supported in March (see https://github.com/dbt-labs/fs/issues/1265 and https://github.com/dbt-labs/fs/pull/1287) so must have regressed?

```
joel@Joel-Labes jinja_profiles_default % dbt parse
dbt-fusion 2.0.0-beta.27
   Loading profiles.yml
error: dbt1501: Failed to eval the compiled Jinja expression invalid operation: cannot convert kwargs to string
(in <expression>:1)
  --> profiles.yml:15:1
  Finished 'parse'  with 1 error in 25ms 109us
```

Removing the `default=` kwarg makes it work.

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
b27 

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**
- open this project [jinja_profiles_default.zip](https://github.com/user-attachments/files/20872482/jinja_profiles_default.zip)

- run `dbt parse`

**Expected behavior**
Default kwarg to be respected

**Operating System and CPU Type (please complete the following information):**
* Mac/Windows/Linux? Mac
* X86 or ARM? ARM
