### ISSUE TITLE
[BUG] `+snowflake_warehouse` config for snapshot not recognized in `dbt_project.yml`

### ISSUE THREAD

**Issue by justin-ramirez-gametime** [dbt-labs/dbt-fusion#280]
**Describe the bug**
I originally had `snowflake_warehouse` config set in a snapshots config file. I moved it to `dbt_project.yml` since the docs and a previous compile with dbt fusion indicated that wasn't the right pace for it. Now in a later version of dbt fusion I am getting a similar warning.

```
warning: dbt1060: Ignored unexpected key `"+snowflake_warehouse"`. YAML path: `your_project.snapshot_group.+snowflake_warehouse`.
  --> dbt_project.yml:595:29
```
**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**

`dbt-fusion 2.0.0-beta.27`

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [X] YES
- [ ] NO

**To Reproduce**
In `dbt_project.yml`

```yml
snapshots:
  your_project:
    group_a:
      +tags: "group_a_tag"
    group_b:
      +tags: "group_b_tag"
      +snowflak_warehouse: "XLARGE_WAREHOUSE"

```

**Expected behavior**
expected the project to compile without warning and recognize this as valid

**Operating System and CPU Type (please complete the following information):**
macbook pro, M1 Pro
