### ISSUE TITLE
[BUG] jinja graph compiling error

### ISSUE THREAD

**Issue by VDFaller** [dbt-labs/dbt-fusion#302]
**Describe the bug**
Possibly related to [#198](https://github.com/dbt-labs/dbt-fusion/issues/198). 
I'm having an issue with compiling when I try to get all exposures via the graph variable in jinja.  

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
beta-30

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**
```yml
version: 2

exposures:
  - name: fusion
    label: DBT - Fusion
    type: dashboard
    maturity: high
    url: https://github.com/dbt-labs/dbt-fusion
    description: An awesome DBT engine
    depends_on:
      - ref('stg_customers')
    owner:
      name: Fake Name
      email: Fake.Name@company.com
```

I tried this two different ways which gives me two different errors. 

```sql
{# all_exposures.sql #}
with all_exposures as (
  {% for exposure in graph.exposures.values() %}
    SELECT 
        '{{exposure.name}}' as name
    {{ 'UNION ALL' if not loop.last }}   
  {% endfor %}
)

SELECT *
FROM all_exposures
-- returns error: dbt0101: no viable alternative at input 'with all_exposures as ()
``` 

```sql
{# all_exposures.sql #}
SELECT *
FROM (
  VALUES 
    {% for exposure in graph.exposures.values() %}
    {{',' if not loop.first}} ('{{exposure.name}}' as name)
    {% endfor %}
) as t(name)
-- returns error: dbt0214: Table 'VALUES' does not exist in schema dev_vince.jaffle_shop
```

**Expected behavior**
Both compile in dbt-databricks 1.10.2 

**Screenshots**

**Operating System and CPU Type (please complete the following information):**
* WSL on Windows 11
* X86
