### ISSUE TITLE
[BUG] `schema` and `database` configs for snapshots in dbt_project.yml are not following `generate_*_name` logic

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-fusion#303]
**Describe the bug**

Both `target_schema` and `schema` (and the same pair for database) ~are~ were valid options for historic reasons. Fusion only supports `schema` and `database` because the others were deprecated. 

The correct behaviour is for the snapshot's schema to be generated according to `generate_schema_name()` (and the same for database). Right now they are always hard-coded to the literal value of `schema`, instead of getting a different schema name for each development environment and production as you'd expect for the default generate_schema_name behaviour. 

```yml
# dbt_project.yml

snapshots: 
  +schema: custom_snapshot_schema
```

```yml
# snapshots/my_snapshot.yml
snapshots:
  - name: snapshot_in_snap_dir
    relation: ref('stg_customers')
    config: 
      strategy: check
      check_cols: ['customer_id']
      unique_key: customer_id
```

> ✅  dbt-core creates `dbt_jlabes_custom_snapshot_schema.snapshot_in_snap_dir` (with the expected `dbt_jlabes` dev prefix)
> :x: fusion creates `custom_snapshot_schema.snapshot_in_seed_dir` (without dev prefix)

Fusion version: b43 

Expected behaviour: 
- Fusion to use `generate_schema_name` and `generate_database_name` for snapshots who have had `schema` or `database` configs set. 
- Note: Fusion already behaves correctly when no custom schema is set. I.e. it builds the snapshot into the default `dbt_jlabes` schema defined in `profiles.yml`.
