### ISSUE TITLE
[BUG] [Snowflake] externalbrowser fails with "MFA with TOTP is required"

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-fusion#316]
**Describe the bug**

A user of Snowflake on GCP is experiencing the following when using dbt Fusion and `authenticator: externalbrowser` with `dbt-fusion 2.0.0-beta.32`

dbt will correctly:
1. spawn a browser window to authenticate
2. create a token and pass it back to `localhost` with `token` URL parameter

However, dbt gets an error from Snowflake that the token is invalid.

```
error: dbt1501: Failed to render SQL invalid operation: AdapterError: ADBC error: [Snowflake] 394508 (08004): Failed to authenticate: MFA with TOTP is required. To authenticate, provide both your password and a current TOTP passcode. (SQLSTATE: 08004, Vendor code: 394508)
(in dbt_internal_packages/dbt-adapters/macros/etc/statement.sql:10)
```

```yml
# ~/.dbt/profiles.yml
default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: XXXXX-XXXXXXX
      user: ryan@suvera.co.uk
      authenticator: externalbrowser
      role: PC_DBT_ROLE
      warehouse: MEDIUM_WH
      database: PC_DBT_DB
      schema: DBT_RPEGGS
      threads: 32
```

the account URL to login
```
https://XXXX.eu-west-2.aws.snowflakecomputing.com/fed/login
```

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
`dbt-fusion 2.0.0-beta.32`
**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

**To Reproduce**

No idea how to reproduce tbh

**Expected behavior**

It should work like it does for Core?

**Screenshots**

**Operating System and CPU Type (please complete the following information):**
* Mac/Windows/Linux?
* X86 or ARM?
