### ISSUE TITLE
DBT vs code extension error

### ISSUE THREAD

**Issue by kaivalya-graas** [dbt-labs/dbt-fusion#71]
After installing dbt vs code extension, getting the error logged in the PROBLEMS tab as follows:

```
dbt1013: YAML error: invalid type: map, expected a string
  --> <unknown>:1:1
```

My dbt configuration is as follows:
1. python version 3.8.10
2. dbt-core version 1.4.5

**Comment by jeremyyeo** [comment]
@kaivalya-graas this can happen when you have some "invalid" values in your yaml... for example:

```yaml
# dbt_project.yml
name: my_dbt_project
profile: sf
version: "1.0.0"

models:
  my_dbt_project:
    +materialized: { a: b } # A map.
```

```sh
$ dbtf parse
dbt-fusion 2.0.0-beta.12
   Loading ~/.dbt/profiles.yml
   Loading dbt_project.yml
   Loading dbt_internal_packages/dbt-adapters/dbt_project.yml
   Loading dbt_internal_packages/dbt-snowflake/dbt_project.yml
error: dbt1013: YAML error: invalid type: map, expected a string
  --> <unknown>
  Finished 'parse'  with 1 error in 276ms 95us
```

As soon as I make that yaml correct:
```yaml
# dbt_project.yml
name: my_dbt_project
profile: sf
version: "1.0.0"

models:
  my_dbt_project:
    +materialized: table # A string.
```

```sh
$ dbtf parse
dbt-fusion 2.0.0-beta.12
   Loading ~/.dbt/profiles.yml
   Loading dbt_project.yml
   Loading dbt_internal_packages/dbt-adapters/dbt_project.yml
   Loading dbt_internal_packages/dbt-snowflake/dbt_project.yml
  Finished 'parse' target 'ci' in 240ms 287us
```

Worth double checking your yamls where you have a "map"/dict when it should actually be a "string".
