### ISSUE TITLE
[FEAT] Reference sharded tables as a source in BigQuery

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-fusion#85]
**Is your feature request related to a problem? Please describe.**

https://docs.getdbt.com/reference/resource-properties/identifier#reference-sharded-tables-as-a-source-in-bigquery

```yaml
version: 2

sources:
  - name: ga
    tables:
      - name: events
        identifier: "events_*"
```

**Is your feature request related to a particular component of the dbt Fusion Engine**
- [] CLI Features
- [x] Adapter or Database Driver Features
- [] SQL Understanding Features

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
