### ISSUE TITLE
[BUG] dbt deps incorrect with multiple subdirectories

### ISSUE THREAD

**Issue by ryan-pip** [dbt-labs/dbt-fusion#90]
**Describe the bug**
dbt deps only finds and loads the first dependency from a git repo when there are multiple subdiretories. We have a mono repo with a dbt project for each source system. These are then imported as packages into the main dbt project. When I run dbt deps it is only adding one of these to the lock file.

**What version of dbt Fusion is this bug in? (find out by running `dbt --version`)**
dbt-fusion 2.0.0-beta.12

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [X] YES
- [] NO

**To Reproduce**
packages.yml
```
packages:
  - git: "https://github.com/abc/foo-bar.git"
    subdirectory: "src/abc/source/salesforce"
    revision: main
    warn-unpinned: false
  - git: "https://github.com/abc/foo-bar.git"
    subdirectory: "src/abc/source/github"
    revision: main
    warn-unpinned: false
```
this results in 
packages-lock.yml
```
packages:
- git: https://github.com/abc/foo-bar.git
  name: salesforce
  revision: |
    605809c448a2f4ac3aa952b2d7268ae629824829
  warn_unpinned: false
  subdirectory: src/abc/source/salesforce
sha1_hash: 7b19cc82aa59df1922a59910af631536e95843d2
```

**Expected behavior**
There should be a dependency per subfolder in both the lockfile and the dbt_packages folder

** Operating System and CPU Type (please complete the following information):**
* Mac
* ARM
